"""Constants"""

DOMAIN = "vmeab"
CONF_SENSOR_UPDATE_INTERVAL = "3600"
CONF_COORDINATOR_UPDATE_INTERVAL = "10800"
CONF_STREET = "street"
CONF_CITY = "city"
CONFIG_FILE = "vmeab.json"
DEVICE_NAME = "VMEAB"
